### PR TITLE
Add org-protocol://capture

### PR DESCRIPTION
**Pull request by khwolf**
Add a second button to send the current page to org-capture via org-protocol://capture.

### CODE REVIEW

**Comment by khwolf** [comment]
Hope the rebase worked out. Thanks for considering the changes!

**Comment by khwolf** [comment]
Hi @vifon,
have you seen the changes and had a chance to look at them? I do not want to nag, just make sure you did not miss it.
Best,
  Klaus Hendrik

**Comment by vifon** [comment]
Actually it somehow slipped through my inbox, so thank you for the message!

I'll take a closer look at your changes later this week.

**Comment by vifon** [comment]
I will want to rework the UI layout a little before merging, as the existing one isn't really suited for more than one action. Adding a `capture` action is a good idea that I already considered not too long ago, so expect it to be merged as soon as I find the time for add these UI tweaks. Thank you!

**Comment by khwolf** [comment]
Thanks! You might consider adding the current selection on the page to the captured URL. I did not find out how to access the selection, as i am not familiar with add-on development and the APIs.

**Comment by vifon** [comment]
I only now saw your last comment after pushing but [it seems we had the same idea here](https://github.com/vifon/org-protocol-for-firefox/commit/1ceac03255d8df4fb723cc3610db94e7e681cfb1#diff-d36d3871f7da7797c0ff0f40dc4d9bfe7c84ab3137095298ddeba8bedf7be748R21-R22). I will also need to research how to achieve it but it would be a nice feature.

I'll push the new version to addons.mozilla.org once I make sure it's all working fine.

**Comment by khwolf** [comment]
Great! Thanks a lot!

**Comment by vifon** [comment]
Good news, I've got the selection extraction working. Regarding the scary new addon permission, see the updated README.

If you'd like to test it already, here's the version I'm currently testing myself: [org_protocol-1.2.99.2-fx.xpi.zip](https://github.com/vifon/org-protocol-for-firefox/files/6065242/org_protocol-1.2.99.2-fx.xpi.zip). The final version will be numbered 1.3, so it should auto-update later with no problems.
Side note: I know zipping an .xpi file is silly (technically it's already a zip) but Github didn't allow me to upload it otherwise.

**Comment by khwolf** [comment]
Great! Have installed it and it looks nice and seems to work fine on Windows10, FF86. Thanks again!

**Comment by vifon** [comment]
FYI, 1.3.0 is on AMO.

**Pull request merged**
